In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
sample_matrix = np.array(list_of_lists)

In [4]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [8]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((2,10),int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.rand(3,2)

array([[0.65992593, 0.44124515],
       [0.22628402, 0.86216667],
       [0.9606569 , 0.09479082]])

In [21]:
np.random.randn(3,2)

array([[ 0.65662778, -0.33253404],
       [ 1.02528114,  0.77646432],
       [ 2.1728365 ,  1.19141359]])

In [22]:
np.random.randint(30,50)

37

In [23]:
np.random.randint(34,100,50)

array([52, 55, 96, 93, 41, 92, 81, 95, 83, 71, 43, 73, 86, 68, 93, 43, 65,
       54, 80, 80, 43, 41, 59, 81, 80, 81, 95, 95, 47, 89, 53, 50, 54, 41,
       66, 49, 81, 35, 74, 85, 74, 34, 45, 98, 46, 78, 72, 85, 55, 97])

In [24]:
rand_array=np.random.randint(0,100,29)
rand_array

array([54, 75, 19, 82, 35, 52,  1, 18, 72, 19, 50,  4, 12, 66, 20, 65, 56,
        5, 61, 10, 96, 59, 45, 17, 99, 36, 98, 19, 16])

In [26]:
sample_array=np.arange(30)

In [29]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [30]:
rand_array.min()

1

In [31]:
rand_array.argmin()

6

In [32]:
a=np.eye(5)

In [33]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a=np.random.rand(2,3)
a

array([[0.52613216, 0.29160185, 0.50417496],
       [0.8823027 , 0.93984054, 0.72578412]])

In [36]:
a.T

array([[0.52613216, 0.8823027 ],
       [0.29160185, 0.93984054],
       [0.50417496, 0.72578412]])

In [37]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
sample_array[3]

13

In [39]:
sample_array[3:7]

array([13, 14, 15, 16])

In [40]:
sample_array[1:4]=100

In [41]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [43]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [50]:
sample_matrix=[[50,34,56],[67,8,9],[45,67,89]]
sample_matrix

[[50, 34, 56], [67, 8, 9], [45, 67, 89]]

In [53]:
sample_matrix=np.array([[34,56,78],[6,67,89],[435,77,867]])
sample_matrix

array([[ 34,  56,  78],
       [  6,  67,  89],
       [435,  77, 867]])

In [54]:
sample_matrix[0:2,2]

array([78, 89])

In [55]:
sample_matrix[2,:]

array([435,  77, 867])

In [56]:
sample_matrix[2]

array([435,  77, 867])

In [59]:
sample_matrix[1,3:2]

array([], dtype=int64)

In [62]:
sample_matrix=np.arange(1,20)

In [63]:
sample_matrix+sample_matrix

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [64]:
np.exp(sample_matrix)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [65]:
np.max(sample_matrix)

19

In [66]:
np.min(sample_matrix)

1

In [67]:
np.argmax(sample_matrix)

18

In [68]:
np.argmin(sample_matrix)

0

In [69]:
np.square(sample_matrix)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [70]:
np.std(sample_matrix)
np.mean(sample_matrix)

10.0